language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

# before_install: 
# install: 

script: "perl Makefile.PL; make test"


notifications:
  recipients:
    - mjdominus@gmail.com
  email:
    on_success: always
    on_failure: always
